name: test-github-actions

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: 'ubuntu-latest'
        container: beckermr/stackvana

        steps:

            - name: Install special dependencies with conda and pip
              shell: bash -l {0}
              run: |
                  . /usr/local/share/stackvana-activate.sh
                  conda install -q -y ngmix meds
                  pip install --no-deps git+https://github.com/LSSTDESC/descwl-shear-sims.git
                  pip install --no-deps git+https://github.com/LSSTDESC/descwl_coadd.git
                  pip install --no-deps git+https://github.com/esheldon/metadetect.git

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Lint with flake8
              shell: bash -l {0}
              run: |
                  . /usr/local/share/stackvana-activate.sh
                  flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                  flake8 . --count --exit-zero --max-line-length=79 --statistics

            - name: Run pytest
              shell: bash -l {0}
              run: |
                  . /usr/local/share/stackvana-activate.sh
                  pytest -vv
