name: test-github-actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
    HOME: /root

jobs:
    build:

        runs-on: 'ubuntu-latest'

        container: beckermr/stackvana

        steps:
            - name: Setup
              shell: bash -l {0}
              run: |
                  cd $HOME
                  . /usr/local/share/stackvana-activate.sh

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install special dependencies with conda and pip
              shell: bash -l {0}
              run: |
                  . /usr/local/share/stackvana-activate.sh
                  conda install -q -y ngmix
                  pip install --no-deps git+https://github.com/LSSTDESC/descwl-shear-sims.git
                  pip install --no-deps git+https://github.com/LSSTDESC/descwl_coadd.git
                  pip install --no-deps git+https://github.com/esheldon/metadetect.git

            - name: Lint with flake8
              shell: bash -l {0}
              run: |
                  . /usr/local/share/stackvana-activate.sh
                  # stop the build if there are Python syntax errors or undefined names
                  flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                  # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                  flake8 . --count --exit-zero --max-line-length=79 --statistics

            - name: Run pytest
              shell: bash -l {0}
              run: |
                  . /usr/local/share/stackvana-activate.sh
                  pytest -vv
